### ISSUE TITLE
Review : Code + rapport

### ISSUE THREAD

**Issue by clementserrano** [PolytechLyon/isi3-singleton-piard-serrano-tp5#1]
Bonjour Monsieur Caron,

Pouvez-vous revoir notre code + rapport et plus particulièrement la partie spring boot où nous utilisons un application.properties ?

Est-ce que le choix du Logger par un paramètre dans application.properties (et la façon dont nous avons check ce param) est OK pour vous ?

Est-ce que c'est possible de modifier le bean, pour choisir un autre logger, en cours d'exécution du programme ? (modifier le .properties)

Merci de vos réponses,

Bien cordialement,
Clément Serrano.

**Comment by Slashgear** [comment]
- [ ] On peut faire de l'autowiring avec spring en xml. Je vous laisse me trouver la conf à setup 😉 

- [ ] Pour votre configuration Springboot, ce qu'il vous manque c'est l'usage des Profil Spring

https://jeanchristophegay.com/spring-et-les-profils/

**Comment by clementserrano** [comment]
Bonjour,

J'ai implémenté les profils avec spring boot, merci c'est très propre :thumbsup:

Pour l'autowire en xml, je rencontre un problème, je suis obligé de définir les beans cat et person dans le xml pour utiliser autowire="byName". Lorsque je met cet attribut dans loggable seulement, il ne fait pas l'autowire de logger dans les classes filles.

https://github.com/PolytechLyon/isi3-singleton-piard-serrano-tp5/blob/a40c086675324c6feeebf85f6202e86442677d02/singleton/src/main/resources/spring-config.xml#L8

**Est-il impossible d'autowire en xml sans définir l'attribut autowire dans toutes les classes filles ?**

Merci d'avance.

**Comment by Slashgear** [comment]
Je ne sais pas trop pourquoi, normalement le but de l'abstraction c'est justement d'éviter de répéter de la conf.

C'est possible de le faire par annotation. Donc je pense qu'il y a une configuration possible par XML 💡 

J'espère qu'avec ce tp vous arrivez mieux à cerner Spring.
